### ISSUE TITLE
layoutChildren runs constantly

### ISSUE THREAD

**Issue by igorshelopaev** [dlsc-software-consulting-gmbh/PickerFX#1]
SegmentSkin<T, S>::layoutChildren runs constantly
Adding nodes to the scenegraph inside the layoutChildren() method trigger infinite circle.
if you comment getChildren().add(cell); everything is fine.

**Comment by dlemmermann** [comment]
Reminder to self: also affects FlexGanttFX.LinksPane.

**Comment by dlemmermann** [comment]
Fixed with Release 1.0.2. Thanks for the tip.
